spring:
  datasource:
    url: jdbc:h2:mem:superfrog
    username: sa
    password:
  profiles:
    active: dev
  jpa:
    show-sql: false

api:
  endpoint:
    base-url: /api/v1

info:
  app:
    name: SuperFrogSchedulerBackend
server:
  port: 80